"use client";

import { LoginButton, LogoutButton, ProfileButton, RegisterButton } from "@/components/buttons.component";
import { useSession } from "next-auth/react";

export const metadata = {
  title: "Churras",
  description: "Generated by André Peixoto",
};

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <head>
        <title>{metadata.title}</title>
        <meta property="og:title" content="My page title" key="title" />
      </head>
      <body>
        <div>
          <LoginButton />
          {JSON.stringify(session?.user)}
          <LogoutButton />
        </div>
      </body>
    </>
  );
}
